# If / else conditions

let score = 75

if score >= 90 {
    print "Grade: A"
}

if score >= 75 {
    print "Grade: B"
}

if score >= 60 {
    print "Passed!"
} else {
    print "Failed."
}

# Equality check
let password = 1234
let input = 1234

if input == password {
    print "Access Granted"
} else {
    print "Access Denied"
}

# Not equal
let a = 10
let b = 20

if a != b {
    print "a and b are different"
}